### ISSUE TITLE
impossible to update existing heroku instance

### ISSUE THREAD

**Issue by sh3raf** [thelovekesh/ghost-v4-on-heroku#20]
node thelovekesh.js

TypeError: Cannot read property 'connection' of undefined
    at exports.Provider.sanitizeDatabaseProperties (/Users/<USER>/Repositories/ghost-v4-on-heroku/node_modules/ghost/core/shared/config/utils.js:103:25)
    at Object.loadNconf (/Users/<USER>/Repositories/ghost-v4-on-heroku/node_modules/ghost/core/shared/config/index.js:54:11)
    at Object.<anonymous> (/Users/<USER>/Repositories/ghost-v4-on-heroku/node_modules/ghost/core/shared/config/index.js:93:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at bootGhost (/Users/<USER>/Repositories/ghost-v4-on-heroku/node_modules/ghost/core/boot.js:250:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ghost-v4-on-heroku@4.2.2 start: `node thelovekesh.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ghost-v4-on-heroku@4.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by thelovekesh** [comment]
@sh3raf I have addressed this issue and created a release with new changes. I hope that release will solve your issues.

Currently, I am closing this issue. If you face any issue please feel free to report it.
