### ISSUE TITLE
Cannot read property 'connection' of undefined 

### ISSUE THREAD

**Issue by OKNoah** [thelovekesh/ghost-v4-on-heroku#7]
I get this

```
TypeError: Cannot read property 'connection' of undefined        
remote: [1G           at exports.Provider.sanitizeDatabaseProperties (/app/node_modules/ghost/core/shared/config/utils.js:103:25)        
remote: [1G           at Object.loadNconf (/app/node_modules/ghost/core/shared/config/index.js:54:11)        
remote: [1G           at Object.<anonymous> (/app/node_modules/ghost/core/shared/config/index.js:93:27)        
remote: [1G           at Module._compile (node:internal/modules/cjs/loader:1092:14)        
remote: [1G           at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)        
remote: [1G           at Module.load (node:internal/modules/cjs/loader:972:32)        
remote: [1G           at Function.Module._load (node:internal/modules/cjs/loader:813:14)        
remote: [1G           at Module.require (node:internal/modules/cjs/loader:996:19)        
remote: [1G           at require (node:internal/modules/cjs/helpers:92:18)        
remote: [1G           at bootGhost (/app/node_modules/ghost/core/boot.js:238:18)
```

Env variables:

```
APP_PUBLIC_URL:        ●●●●●●.●●●.●●●●●.●●●
DATABASE_URL:          mysql://mysql:●●●●●●●●●●●●@dokku-mysql-●●●●●●:3306/●●●●●●
DOKKU_APP_TYPE:        herokuish
MAILGUN_API_KEY:       ●●●-●●●●●●●●●●
MAILGUN_DOMAIN:        ●●●●●.●●●●●●●.●●●
MAILGUN_PUBLIC_KEY:    ●●●●●●●-●●●●●●●●●●●●●●●●●●●●
MAILGUN_SMTP_LOGIN:    postmaster@●●●●●.●●●●●●.●●●
MYSQL_DATABASE_URL:    mysql://mysql:●●●●●●●●●●●●@dokku-mysql-●●●●●●:3306/●●●●●●
S3_ACCESS_KEY_ID:      ●●●●●●●●●●●●●●●●●●●●
S3_ACCESS_SECRET_KEY:  ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
S3_ASSET_HOST_URL:     ●●●●●●.ap-south-1.●●●●●●.●●●
S3_BUCKET_NAME:        ●●●●●●
S3_BUCKET_REGION:      ap-south-1
```

**Comment by thelovekesh** [comment]
`DOKKU_APP_TYPE` where it comes from?

**Comment by thelovekesh** [comment]
Actually, it's not an issue with the deployment from this repo.
You can ask your question here - https://ask.codebulbs.com/

**Comment by OKNoah** [comment]
> Actually, it's not an issue with the deployment from this repo.
> You can ask your question here - https://ask.codebulbs.com/

Hope you don't mind me asking something about the design here. Is it the case that the configuration file is generated during install? So simply trying to run it would do so without a configuration and fail to create the `connection`. Some Heroku step runs the configuration creation. Perhaps committing the config file or creating a volume fo the file/folder it's in, outside the generated container would work? Am I on the right track?

**Comment by thelovekesh** [comment]
Yes, Heroku is creating the config file during the deployment. Do you want to deploy the project with the self-created file?

**Comment by thelovekesh** [comment]
Closing this issue due to inactivity.

**Comment by keyuls** [comment]
@OKNoah  Did you find the solution for this?
